language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 5.7
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  - DB=mysql

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

script: phpunit --configuration phpunit_$DB.xml --coverage-text
