language: php

sudo: false

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise

before_script:
  - mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot;
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit.xml --coverage-text
